services:
  # Base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: inazuma-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-inazuma_password}
      POSTGRES_DB: ${POSTGRES_DB:-inazuma_market}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: inazuma-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: