-- AlterTable
ALTER TABLE "GameSettings" ADD COLUMN "basePlayerPrice" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "GameSettings" ADD COLUMN "playerPricePerLevel" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "GameSettings" ADD COLUMN "baseCoachPrice" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "GameSettings" ADD COLUMN "coachPricePerLevel" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "GameSettings" ADD COLUMN "playerPricePerPc" INTEGER NOT NULL DEFAULT 1;
